name: ELSEWHR Vercel deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npm install -g vercel@50.4.4
      - run: vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
      - run: vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
      - run: vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
